services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - my-mysql-data:/var/lib/mysql
volumes:
  my-mysql-data: