#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="/workspaces/${LOCAL_WORKSPACE_FOLDER:-$(basename $(pwd))}/.env"
JWT_SECRET=$(openssl rand -base64 32)

DB_PORT=3306
DB_PORT_TEST=3306
DB_USER=mysql
DB_PASS=mysql
DB_NAME=db_desafio
DB_NAME_TEST=db_desafio_test

DB_URL="mysql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}"
DB_URL_TEST="mysql://${DB_USER}:${DB_PASS}@db_test:${DB_PORT_TEST}/${DB_NAME_TEST}"

cat > "$ENV_FILE" <<EOF
# Generated by .devcontainer/generate-env.sh
JWT_SECRET="${JWT_SECRET}"
DB_URL="${DB_URL}"
DB_URL_TEST="${DB_URL_TEST}"
EOF
echo ".env generated at $ENV_FILE"
